name: balda
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.4.3+7
  flutter_lints: ^2.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  image_picker: ^0.8.5+3
  infinite_scroll_pagination: ^3.2.0
  jwt_decoder: ^2.0.1
  modal_bottom_sheet: ^2.0.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.2
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  cloud_firestore: ^3.4.7
  firebase_core: ^1.22.0
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#2057A6"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
